# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/028_anthropic_test.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../nbs/028_anthropic_test.ipynb 2
from anthropic import Anthropic, AsyncAnthropic
from pydantic import BaseModel
from singleton_decorator import singleton
import asyncio
from .core import load_env
import logging

# %% ../nbs/028_anthropic_test.ipynb 3
load_env()
logger = logging.getLogger(__name__)
