# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/027_mcp.ipynb.

# %% auto 0
__all__ = ['mcp_tool_executor_factory']

# %% ../nbs/027_mcp.ipynb 6
import asyncio
import nest_asyncio
import json
import os
from typing import Tuple, List, Dict, Any, Optional
from contextlib import asynccontextmanager,AsyncExitStack

from fastmcp import Client, FastMCP
from fastmcp.client.transports import StreamableHttpTransport, PythonStdioTransport ,StdioTransport 


from anthropic import Anthropic

from openai import AsyncOpenAI

# %% ../nbs/027_mcp.ipynb 27
def mcp_tool_executor_factory(mcp_client):
    """
    Factory function that creates an execute_mcp_tool function bound to a specific mcp_client.
    
    Args:
        mcp_client: The MCP client instance to use for tool execution
        
    Returns:
        An async function that executes tools using the provided client
    """
    async def execute_mcp_tool(tool):
        """
        Extracts the tool name and arguments from the tool dict,
        executes the tool via mcp_client, and returns both:
          1. the OpenAI tool_result-style message, and 
          2. the raw tool_result itself.
        """
        tool_name = tool['name']
        tool_args = tool['input']
        tool_id = tool['id']
        async with mcp_client:
            tool_result = await mcp_client.call_tool(tool_name, tool_args)
        # Extract text from content objects to make it serializable
        content_texts = [item.text for item in tool_result.content if hasattr(item, 'text')]
        return {
            "tool_name": tool_name,
            "tool_args": tool_args,
            "tool_id": tool_id,
            "tool_content_texts": content_texts,
        }
    return execute_mcp_tool
