# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/docs/examples/009_mcp_agent.ipynb.

# %% auto 0
__all__ = ['system_message', 'tool_selector', 'has_tool_calls', 'MCP_Chat_factory', 'has_tool_result']

# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 4
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from .. import Define, V, E, Condition, Scope
from ..chat import Chat
import os

from fastmcp import Client
import asyncio


# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 11
# Chat node for tool selection with MCP tools
system_message =[{
    "role": "system",
    "content": f"""You have access to filesystem tools. 
    
The following directories are available to you:
{sample_data_loc}
IMPORTANT: When using filesystem tools, you MUST use absolute paths that start with one of the allowed directories above. 

For example:
- CORRECT: "/Users/olgasoldatenko/work/newer/stringdale/sample_data/wiki/dogs.md"
- WRONG: "wiki/dogs.md" or "dogs.md"
"""
}]
# This chat will be used in the diagram to select tools
tool_selector = Chat(
    model="gpt-4o-mini",
    init_messages=system_message,
    mcp_tools=mcp_tools,
)


# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 20
# Condition to check if tools were selected
#we would do for each in a diagram
# Condition if use tools otherwise end
def has_tool_calls(llm_response):
    if 'tool_calls' in llm_response:
        tool_call = llm_response['tool_calls']
        if tool_call != []:
            return True
        else:
            return False
    return False



# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 22
def MCP_Chat_factory(mcp_tool_selector_chat,execute_mcp_tool):
    # Factory that returns the MCP Agent diagram definition
    with Define('MCP Agent', type='decision') as MCP_Chat:
        # Start: User query comes in
        # Select tool: Chat with MCP tools to decide which tool to use
        V('select_tool', mcp_tool_selector_chat,
          inputs=['Start(messages=.)'],
          outputs=[
              ('format_chat_messages'),
              ('Start_flow(tools=content)', Condition(has_tool_calls, '(llm_response=content)'))
          ])
        V('format_chat_messages', format_chat_messages,
          outputs=['End(messages = .)'])
        # Execute the selected tool
        V('Start_flow',
        )
        with Scope('flow'):
            V('execute_tool', execute_mcp_tool,
              inputs=['Start_flow(tool = tools.tool_calls)'],
              outputs=['End_flow'],
              for_each=['tool']
            )
            # Format the final answer for the user
        V('End_flow',format_tool_output,
          outputs=['End(messages = .)'])
    return MCP_Chat

# %% ../../nbs/docs/examples/009_mcp_agent.ipynb 31
def has_tool_result(mcp_output: Dict[str, Any]) -> bool:
    """
    Check if the mcp_chat output contains at least one tool_result in messages.
    
    Args:
        mcp_output: Output from mcp_chat sub-diagram, should have a 'messages' key
        
    Returns:
        True if any message has content with type 'tool_result', False otherwise
    """    
    messages = mcp_output.get('messages', [])
    # Iterate through each message
    for message in messages:
        if not isinstance(message, dict):
            continue
            
        content = message.get('content', [])
        
        # Handle content as a list
        if isinstance(content, list):
            for item in content:
                if isinstance(item, dict) and item.get('type') == 'tool_result':
                    return True
        
        # Handle content as a string (no tool_result)
        elif isinstance(content, str):
            continue
    
    return False
